<?php
	session_start();
	$host="localhost";
	$username="root";
	$password="";
	$dbname="hospital_management";
	$conn=mysqli_connect($host,$username,$password,$dbname);
	session_unset();
	session_destroy();
	header("location:pharmacylogin.php");
?>